### ISSUE TITLE
Does not write to s3 if redshift is unavailable

### ISSUE THREAD

**Issue by mattty** [hapyrus/fluent-plugin-redshift#14]
I had expected that this plugin would write to s3 if redshift was unavailable, but this does not seem to be the case. Is this expected behaviour? How can I ensure that data is written to s3 (and the buffer cleared) if redshift is unavailable (e.g. due to resize operation running on cluster)?

**Comment by gerricchaplin** [comment]
Hi Matt,

I think the point of td-agent/fluent is to buffer locally when resources are not available. And that is exactly what you want during things like cluster resize. If files get written to S3 then a record would have to be kept of which files were written and which were loaded or not loaded. This seems like a lot more overhead for not much gain and it's not the way td-agent usually does things.

This of course is an issue when it comes to your instance going down so I would recommend using the S3 plugin alongside the Redshift plugin. You can do this with a copy directive to ensure your logs always get sent to S3 for backup purposes and those logs that can get loaded are loaded into Redshift. If something happens and you end up not loading some logs you will hopefully have them in S3 and can transform and load them outside of td-agent.

I hope that helps.
Gerric
