### ISSUE TITLE
Switch to PG async connect_start

### ISSUE THREAD

**Issue by bwilliams** [hapyrus/fluent-plugin-redshift#15]
There are two lines where you connect to redshift with PG.connect.

For some reason, these occasionally hang forever, and we need to restart fluentd to recover, as the entire process gets blocked.

I've noticed that there is now an asynchronous version PGconn.connect_start that immediately gives you a connection object that you can poll to ask when it is ready. Could you please switch to that API and raise an exception if it doesn't become available after some timeout? That way fluentd can log an error and invoke its existing retry behaviors.

**Comment by mmasashi** [comment]
You're right, PG api with sync mode blocks other threads literally. I will work on it to fix this issue.

**Comment by mmasashi** [comment]
Fixed with https://github.com/hapyrus/fluent-plugin-redshift/commit/3e38651f73aa3dedfcd7931206930a300457f87c
