### ISSUE TITLE
Requires aws-sdk-v1 Library?

### ISSUE THREAD

**Issue by mansours** [hapyrus/fluent-plugin-redshift#20]
I found it hangs on S3 connection attempts on line 74.
Perhaps because it was written with the old sdk?

Workaround is you can install the v1 sdk and replace a line in the .rb file.

do a "gem install aws-sdk-v1" from the command line,
then in out_redshit.rb replace **require 'aws-sdk'** with **require 'aws-sdk-v1'** on line 12

**Comment by mmasashi** [comment]
Thanks for the ticket.  Already fixed with #16 . I will release the next version including this soon.
